### ISSUE TITLE
Question about the updated version

### ISSUE THREAD

**Issue by maisuiqianxun** [Graph-Machine-Learning-Group/grin#10]
Hi authors, thank you for releasing the open-source code of GRIN, which is a great work. However, when I adjust two operations in the code, the performance of the model get extremely worse. Would you mind helping me figure out the reason of this phenomenon? The details of revised operations are summarized as follows:

1. replace the code " out = self.graph_conv(x_in, adj)" in lines 43 of file "https://github.com/Graph-Machine-Learning-Group/grin/blob/main/lib/nn/layers/gril.py" with "out = x_in"
2. replace the code " x_s = torch.where(m_s, x_s, xs_hat_1) " in lines 152 of file " https://github.com/Graph-Machine-Learning-Group/grin/blob/main/lib/nn/layers/gril.py" with "x_s = x_s". That is, comment out this line of code.

If the above two operations are adopted, the performance will get extremely worse; If only the one operation is adopted, the performance will get slightly worse. Then, can you explain the reason of these phenomenon?

By the way, the experiment is tested with setting: "python ./scripts/run_imputation.py --config config/grin/la_point.yaml"

**Comment by maisuiqianxun** [comment]
@marshka @andreacini

**Comment by andreacini** [comment]
The fact that results get worse by performing those two modifications shouldn't be a surprise. In particular, the first modification actually corresponds to one of the ablation studies in the paper and if you remove the second operation you are not replacing missing values with predictions in the autoregressive processing of the input.

**Comment by maisuiqianxun** [comment]
Thanks for your reply. If missing values are not replaced by predictions (modification 2), and remove the convolution layer (modification 1) in the meantime, the MAE curve on the training set is expected as the following figure?
![result](https://user-images.githubusercontent.com/31894973/208854992-9cb1a866-7f17-4de3-a311-3116099510e7.png)

**Comment by maisuiqianxun** [comment]
I get it, thx!
