### ISSUE TITLE
6500 sensors

### ISSUE THREAD

**Issue by ucsky** [Graph-Machine-Learning-Group/grin#3]
Hello,
Thanks for providing this code.
Can this model scale to a system with 6500 time series?

**Comment by marshka** [comment]
Hi!

Thanks for your interest in our work. In general yes, it can scale. If you mean in terms of memory/computational requirements, consider that even in the largest dataset tested (485 nodes and 4365 edges) it fits in an 8GB GPU (of course, the larger the dataset, the slower the inference procedure). In terms of model performance, thanks to the graph-based approach imputations are regularized considering neighboring nodes, such that a small sub-region of the entire network contribute the most to the central node representation. This allows for more robustness and way fewer parameters on large graphs with respect to approaches that do not take into account the topology.

If you are interested in working on this topic, consider using [Torch Spatiotemporal](https://github.com/TorchSpatiotemporal/tsl), our library on neural spatiotemporal processing, where you can also find an updated implementation of GRIN.

Cheers,

Ivan

**Comment by ucsky** [comment]
Hi Ivan,

Great I will look into it.

Cheers,
Guillaume
