### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by HaominYu0** [Graph-Machine-Learning-Group/grin#4]
I met some problems when I click the link to download the datasets.  I cannot open the download page by clicking the link.

Hope to get some help!

**Comment by marshka** [comment]
Hi!

Thanks for your interest in our work. I just checked the MEGA link published in the readme and they work for me.

If you still have problems downloading the datasets, consider using [Torch Spatiotemporal](https://github.com/TorchSpatiotemporal/tsl), our library on neural spatiotemporal processing. It comes with an updated GRIN implementation, along with the datasets used for this paper.

Cheers,

Ivan
