### ISSUE TITLE
Testing GRIN on a new dataset

### ISSUE THREAD

**Issue by RoufaidaLaidi** [Graph-Machine-Learning-Group/grin#7]
Hello, 
Thanks for sharing the code for the paper. I would like to test GRIN for imputation on my own dataset. The dataset is presented in a csv file and I create the mask that simulates the missing data using a random function. Can you indicate to me how to proceed to include my own dataset? Thanks in advance.

**Comment by andreacini** [comment]
Hi! Sorry for the late reply, you should wrap your dataset in a class similar to those in lib/datasets.

I also suggest you check our [library](https://github.com/TorchSpatiotemporal/tsl), where you'll find updated code for GRIN and other methods.
